### ISSUE TITLE
Contribute module to Any23 project?

### ISSUE THREAD

**Issue by lewismc** [frankier/any23jena#1]
Hi @frankier
I recently stumbled across this library 👍 
Are you interested in contributing it to the Any23 project? Due to the large dependency on Jena we could include it as a separate module. 
Thanks for your consideration.

**Comment by lewismc** [comment]
I created https://issues.apache.org/jira/browse/ANY23-545 if you are keen to advance conversation. Thanks

**Comment by frankier** [comment]
Hi @lewismc !

Yes I would be very happy to have it included in Any23, where perhaps it may get some more usage. However my Java / semantic web skills are a bit decayed -- I wrote this code as part of a compulsory University course. As you can see, it's there's not very much code here. In terms of lines of code doing stuff rather than Java boilerplate, it must be less than 10. I have no idea if there are any caveats to what I did since I basically wrote just enough to complete the assignment.

Therefore, please go ahead, but I probably can't help beyond what is already here.

**Comment by lewismc** [comment]
Hi @frankier 

> ...As you can see, it's there's not very much code here.

That's fine we can build on what you've implemented. I was studying the code last night and I think this would be a nice addition.

> ...I have no idea if there are any caveats

Yes there are a few but I can iron those out.

OK I'll close off this ticket once this new feature is implemented. Thanks

**Comment by lewismc** [comment]
I'm going to take this over to the Any23 JIRA for any further discussion. Thanks @frankier
